


/*
 * Ben Oosterhuis
 * 03/03/2020
 * This program is my version of a math multiple choice quiz
 */

/**
 *
 * @author Ben
 */
public class QuizFrame extends javax.swing.JFrame {

    public QuizFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        q1A = new javax.swing.JLabel();
        q1B = new javax.swing.JLabel();
        q1C = new javax.swing.JLabel();
        q1D = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        q2A = new javax.swing.JLabel();
        q2B = new javax.swing.JLabel();
        q2C = new javax.swing.JLabel();
        q2D = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        q3A = new javax.swing.JLabel();
        q3C = new javax.swing.JLabel();
        q3B = new javax.swing.JLabel();
        q3D = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        q4A = new javax.swing.JLabel();
        q4C = new javax.swing.JLabel();
        q4D = new javax.swing.JLabel();
        q4B = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        q5A = new javax.swing.JLabel();
        q5B = new javax.swing.JLabel();
        q5C = new javax.swing.JLabel();
        q5D = new javax.swing.JLabel();
        firstAnswer = new javax.swing.JTextField();
        secondAnswer = new javax.swing.JTextField();
        thirdAnswer = new javax.swing.JTextField();
        fourthAnswer = new javax.swing.JTextField();
        fifthAnswer = new javax.swing.JTextField();
        submitQ1 = new javax.swing.JButton();
        submitQ2 = new javax.swing.JButton();
        submitQ3 = new javax.swing.JButton();
        submitQ4 = new javax.swing.JButton();
        submitQ5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        result1 = new javax.swing.JLabel();
        correctAnswers = new javax.swing.JLabel();
        incorrectAnswers = new javax.swing.JLabel();
        percentCorrect = new javax.swing.JLabel();
        result2 = new javax.swing.JLabel();
        result3 = new javax.swing.JLabel();
        result4 = new javax.swing.JLabel();
        result5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(0, 255, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Math Quiz");

        jLabel2.setText("Question 1: What is  9 + 10 equal to?");

        q1A.setText("A: 21");

        q1B.setText("B: -19");

        q1C.setText("C: 19");

        q1D.setText("D: 1");

        jLabel7.setText("Question 2: What is 9 - 4 equal to?");

        q2A.setText("A: 5");

        q2B.setText("B: 6");

        q2C.setText("C: 13");

        q2D.setText("D: -5");

        jLabel12.setText("Question 3: What is 5 x 6 equal to?");

        q3A.setText("A: 36");

        q3C.setText("C: 25");

        q3B.setText("B: 30");

        q3D.setText("D:20");

        jLabel17.setText("Question 4: What is 18 ÷ 6 equal to? ");

        q4A.setText("A: 4");

        q4C.setText("C: 6");

        q4D.setText("D: 3");

        q4B.setText("B: 2");

        jLabel22.setText("Question 5: What is the value of \"x\" in the equation 2x = 4");

        q5A.setText("A: 4");

        q5B.setText("B: xy");

        q5C.setText("C: 2");

        q5D.setText("D: 2x");

        submitQ1.setText("Submit Answer");
        submitQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitQ1ActionPerformed(evt);
            }
        });

        submitQ2.setText("Submit Answer");
        submitQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitQ2ActionPerformed(evt);
            }
        });

        submitQ3.setText("Submit Answer");
        submitQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitQ3ActionPerformed(evt);
            }
        });

        submitQ4.setText("Submit Answer");
        submitQ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitQ4ActionPerformed(evt);
            }
        });

        submitQ5.setText("Submit Answer");
        submitQ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitQ5ActionPerformed(evt);
            }
        });

        result1.setText("Result");

        correctAnswers.setText("Correct Answers: 0");

        incorrectAnswers.setText("Incorrect Answers: 0");

        percentCorrect.setText("Percent Correct: 0.0%");

        result2.setText("Result");

        result3.setText("Result");

        result4.setText("Result");

        result5.setText("Result");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q5B)
                            .addComponent(q5A))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q5C)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(q5D)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(fifthAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(submitQ5)
                                .addGap(18, 18, 18)
                                .addComponent(result5)
                                .addGap(41, 41, 41))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(q1A)
                                .addGap(18, 18, 18)
                                .addComponent(q1C))
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(q2A)
                                .addGap(18, 18, 18)
                                .addComponent(q2C))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(q4A)
                                .addGap(18, 18, 18)
                                .addComponent(q4C))
                            .addComponent(jLabel22)
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(q3A)
                                .addGap(18, 18, 18)
                                .addComponent(q3C))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(q4B)
                                        .addGap(18, 18, 18)
                                        .addComponent(q4D)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fourthAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(q3B)
                                        .addGap(18, 18, 18)
                                        .addComponent(q3D)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(thirdAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(q2B)
                                        .addGap(18, 18, 18)
                                        .addComponent(q2D)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(secondAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(q1B)
                                        .addGap(18, 18, 18)
                                        .addComponent(q1D)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(firstAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(submitQ1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(result1))
                                            .addComponent(jLabel3)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(submitQ2)
                                        .addGap(18, 18, 18)
                                        .addComponent(result2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(submitQ3)
                                        .addGap(18, 18, 18)
                                        .addComponent(result3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(submitQ4)
                                        .addGap(18, 18, 18)
                                        .addComponent(result4))))
                            .addComponent(correctAnswers, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(incorrectAnswers)
                            .addComponent(percentCorrect))
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1A)
                    .addComponent(q1C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1B)
                    .addComponent(q1D)
                    .addComponent(firstAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitQ1)
                    .addComponent(jLabel3)
                    .addComponent(result1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2A)
                    .addComponent(q2C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2B)
                    .addComponent(q2D)
                    .addComponent(secondAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitQ2)
                    .addComponent(result2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3A)
                    .addComponent(q3C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3B)
                    .addComponent(q3D)
                    .addComponent(thirdAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitQ3)
                    .addComponent(result3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q4A)
                    .addComponent(q4C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q4D)
                    .addComponent(q4B)
                    .addComponent(fourthAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitQ4)
                    .addComponent(result4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q5A)
                    .addComponent(q5C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q5B)
                    .addComponent(q5D)
                    .addComponent(fifthAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitQ5)
                    .addComponent(result5))
                .addGap(18, 18, 18)
                .addComponent(correctAnswers)
                .addGap(18, 18, 18)
                .addComponent(incorrectAnswers)
                .addGap(18, 18, 18)
                .addComponent(percentCorrect)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // These are the global variables
    public int correct = 0;
    public int incorrect = 0;
    public int totalAttempts = 0;
    
    // Section of code for the first question
    private void submitQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitQ1ActionPerformed
        String answer = firstAnswer.getText();
        firstAnswer.setEditable( false );
        firstAnswer.setEnabled( false );
        submitQ1.setEnabled( false );
        
        if (answer.equals ("C") || answer.equals ("c")) {
            result1.setText("Correct");
            correct = correct + 1;
        } 
        else
        {
            result1.setText("Incorrect");
            incorrect = incorrect + 1;
        }
        correctAnswers.setText("Correct answers: " + correct );
        incorrectAnswers.setText( "Incorrect answers: " + incorrect);
        percentCorrect.setText( String.format( "Percent Correct: %2.1f%%", 100.0 * correct / 5.0 ));
      

    }//GEN-LAST:event_submitQ1ActionPerformed
    // Section of code for the second question
    private void submitQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitQ2ActionPerformed
        String answer = secondAnswer.getText();
        secondAnswer.setEditable( false );
        secondAnswer.setEnabled( false );
        submitQ2.setEnabled( false );
        
        if (answer.equals ("A") || answer.equals ("a")) {
            result2.setText("Correct");
            correct = correct + 1;
        } 
        else
        {
            result2.setText("Incorrect");
            incorrect = incorrect + 1;
        
        }
        correctAnswers.setText("Correct answers: " + correct );
        incorrectAnswers.setText( "Incorrect answers: " + incorrect);
        percentCorrect.setText( String.format( "Percent Correct: %2.1f%%", 100.0 * correct / 5.0 ));
    }//GEN-LAST:event_submitQ2ActionPerformed
    //Section of code for the third question
    private void submitQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitQ3ActionPerformed
    String answer = thirdAnswer.getText();
        thirdAnswer.setEditable( false );
        thirdAnswer.setEnabled ( false );
        submitQ3.setEnabled ( false );
        
        if (answer.equals ("B") || answer.equals ("b")) {
            result3.setText("Correct");
            correct = correct + 1;
        } 
        else
        {
            result3.setText("Incorrect");
            incorrect = incorrect + 1;
        
        }
        correctAnswers.setText("Correct answers: " + correct );
        incorrectAnswers.setText( "Incorrect answers: " + incorrect);
        percentCorrect.setText( String.format( "Percent Correct: %2.1f%%", 100.0 * correct / 5.0 ));    
    }//GEN-LAST:event_submitQ3ActionPerformed
    //Section of code for the fourth question
    private void submitQ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitQ4ActionPerformed
        String answer = fourthAnswer.getText();
        fourthAnswer.setEditable( false );
        fourthAnswer.setEnabled ( false );
        submitQ4.setEnabled ( false );
        
        if (answer.equals ("D") || answer.equals ("d")) {
            result4.setText("Correct");
            correct = correct + 1;
        } 
        else
        {
            result4.setText("Incorrect");
            incorrect = incorrect + 1;
        
        }
        correctAnswers.setText("Correct answers: " + correct );
        incorrectAnswers.setText( "Incorrect answers: " + incorrect);
        percentCorrect.setText( String.format( "Percent Correct: %2.1f%%", 100.0 * correct / 5.0 ));
    }//GEN-LAST:event_submitQ4ActionPerformed
    //Section of code for the fifth question
    private void submitQ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitQ5ActionPerformed
        String answer = fifthAnswer.getText();
        fifthAnswer.setEditable( false );
        fifthAnswer.setEnabled ( false );
        submitQ5.setEnabled ( false );

        
        if (answer.equals ("C") || answer.equals ("c")) {
            result5.setText("Correct");
            correct = correct + 1;
        } 
        else
        {
            result5.setText("Incorrect");
            incorrect = incorrect + 1;
        
        }
        correctAnswers.setText("Correct answers: " + correct );
        incorrectAnswers.setText( "Incorrect answers: " + incorrect);
        percentCorrect.setText( String.format( "Percent Correct: %2.1f%%", 100.0 * correct / 5.0 ));
    }//GEN-LAST:event_submitQ5ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correctAnswers;
    private javax.swing.JTextField fifthAnswer;
    private javax.swing.JTextField firstAnswer;
    private javax.swing.JTextField fourthAnswer;
    private javax.swing.JLabel incorrectAnswers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel percentCorrect;
    private javax.swing.JLabel q1A;
    private javax.swing.JLabel q1B;
    private javax.swing.JLabel q1C;
    private javax.swing.JLabel q1D;
    private javax.swing.JLabel q2A;
    private javax.swing.JLabel q2B;
    private javax.swing.JLabel q2C;
    private javax.swing.JLabel q2D;
    private javax.swing.JLabel q3A;
    private javax.swing.JLabel q3B;
    private javax.swing.JLabel q3C;
    private javax.swing.JLabel q3D;
    private javax.swing.JLabel q4A;
    private javax.swing.JLabel q4B;
    private javax.swing.JLabel q4C;
    private javax.swing.JLabel q4D;
    private javax.swing.JLabel q5A;
    private javax.swing.JLabel q5B;
    private javax.swing.JLabel q5C;
    private javax.swing.JLabel q5D;
    private javax.swing.JLabel result1;
    private javax.swing.JLabel result2;
    private javax.swing.JLabel result3;
    private javax.swing.JLabel result4;
    private javax.swing.JLabel result5;
    private javax.swing.JTextField secondAnswer;
    private javax.swing.JButton submitQ1;
    private javax.swing.JButton submitQ2;
    private javax.swing.JButton submitQ3;
    private javax.swing.JButton submitQ4;
    private javax.swing.JButton submitQ5;
    private javax.swing.JTextField thirdAnswer;
    // End of variables declaration//GEN-END:variables
}
